version: "3.7"

services:
  Lumos:
    image: docker.io/mduchalski/lumos
    ports:
      - 17154:443
    environment:
      - DB_SERVER=actina15.maas
      - DB_NAME=BE_171547
      - DB_USER=BE_171547
      - DB_PASSWD=lampexpol
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=localhost:17154
      - PS_LANGUAGE=pl
      - PS_COUNTRY=PL
      - PS_FOLDER_ADMIN=admin1
      - PS_ENABLE_SSL=1
    volumes:
      - Lumos:/var/www/html
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  Lumos:
